name: Python Application Workflow Jobs bcancer test Model

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executer bcancer
      run: python3 bcancer.py

    - name: Creer un artefact pour stocker model.pkl
      uses: actions/upload-artifact@v2
      with:
        name: trained_model
        path: model.pkl

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Loader l'artefact model.pkl
      uses: actions/download-artifact@v2
      with:
        name: trained_model
        path: .

    - name: Executer test.py
      run: python3 test.py