name: Python Application Workflow Env

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Afficher Greeting dans le job 1 step 1
      env:
        GREETING: 'Hello !'
      run: echo $GREETING

    - name: Afficher Greeting dans le job 1 step 2
      run: echo $GREETING

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Afficher Greeting dans le job 2
      run: echo $GREETING
